### ISSUE TITLE
Plugin not working anymore

### ISSUE THREAD

**Issue by aymannajim** [Torca2001/MultiSelect#11]
There is no "Move X users here" button.
The script broke somewhere in between the latest Discord updates.
![image](https://github.com/Torca2001/MultiSelect/assets/36258300/768ed814-341a-4b78-b23a-e3d2a7be9c28)

**Comment by Torca2001** [comment]
I haven't been able to reproduce this.
Keep in mind the option will only appear if you have permission to move the users.

**Comment by Torca2001** [comment]
Closing due to lack of info and unable to reproduce

**Comment by aymannajim** [comment]
I am the owner of the server, what info do you need? It's not working!
I'm on Windows 10, I have Better Discord with no other plugins, only your Multi Select plugin installed.
