### ISSUE TITLE
No option to move users

### ISSUE THREAD

**Issue by themegaxandy** [Torca2001/MultiSelect#13]
After the latest Discord update, the move option on the context menu is gone, but the selection works.

![image](https://github.com/Torca2001/MultiSelect/assets/7902295/a870e1a8-9d02-4e24-8112-a1265d5270e7)

**Comment by Torca2001** [comment]
Identified the issue, working on a fix.
Hopefully this is also the cause for #12

**Comment by Torca2001** [comment]
Should be fixed with latest update #14
