### ISSUE TITLE
issue with moving people to channels

### ISSUE THREAD

**Issue by Hexishu** [Torca2001/MultiSelect#2]
So selecting with shift works, the people who gets selected are being marked with a blue box, but when trying to rightclick on a voice channel, it doesn't show move them there(the last option)

**Comment by Torca2001** [comment]
I'm working on it, issue with the changes in discords context menus

**Comment by Hexishu** [comment]
> I'm working on

Thanks:D appreciate it :)

**Comment by Torca2001** [comment]
Fixed in 0c05f7f8158f27084ff1f781c7289d3e114bfa26
