### ISSUE TITLE
Can't compile since BD 1.8.0

### ISSUE THREAD

**Issue by amau05** [Torca2001/MultiSelect#3]
Hi
The plugin can't compile since Discord made all it's internal changes and betterdiscord's plugins had all failed. BD has since fixed it's internal issues since and most plugins works now but not this one
Any chance we get a fix?

**Comment by Torca2001** [comment]
I've stopped the compilation errors but the plugin is still broken. I have been quite busy so I will get around to fixing the plugin once I find some free time.

**Comment by Torca2001** [comment]
Fixed in #5
