### ISSUE TITLE
Request enhancement : mouse drawable area

### ISSUE THREAD

**Issue by albyalex96** [Torca2001/MultiSelect#6]
As **BD update 1.8.4** ( which fixes context menus ) the plugin is working **again** , for the time being. Therefore i wanna suggest a really useful enhancement for this plugin ( which i consider a life saver ) : by pressing shift / ctrl and drawing an area with the mouse , i wanna be able to select all the user within that area in order to move them, and, if possible, i wanna be able to draw areas even between different voice channels .

**Comment by Torca2001** [comment]
Seems interesting, I am still trying to fix the ability to shift/ctrl clicking a voice channel and selecting everyone in it.
But this idea also seems quite plausible I will have to look into it, thanks for the idea.

**Comment by Torca2001** [comment]
It was easier to implement this than it was to fix the ability to click on channels.
Implemented in #7
