### ISSUE TITLE
Any Update 

### ISSUE THREAD

**Issue by iGetUploaded** [Torca2001/MultiSelect#9]
Any update to this or naw?

**Comment by Torca2001** [comment]
I'm been quite busy and from my understanding the plugin works with the ctrl/shift clicking of users and being able to move them.
Or drag clicking to select multiple.

**Comment by iGetUploaded** [comment]
I tried ctrl/shift on my 2 alts & then move to a different channel but only of them gets moved to the other channel

**Comment by Torca2001** [comment]
I can't seem to reproduce this.
Do you have necessary move permissions?
Is the user being selected correctly, does it say move 2?
Is the only one moving the user who is issuing the mass move?

**Comment by iGetUploaded** [comment]
https://user-images.githubusercontent.com/54633753/235277431-5f04100b-514c-4623-975c-017a62a7b28a.mp4

Also says not working atm 
![image](https://user-images.githubusercontent.com/54633753/235277690-44c3b1a7-135c-4aa2-bc69-128223bceab9.png)

**Comment by Torca2001** [comment]
Oh I haven't updated the description my bad.
![image](https://user-images.githubusercontent.com/26198364/235277899-75e704e4-bad8-4a0c-8577-029ae2c266c2.png)
Right click on the destination channel, there should be an option at the bottom to "Move 2 here"

**Comment by iGetUploaded** [comment]
Ahh okay I was clicking the wrong area it works now ty bro

**Comment by Torca2001** [comment]
No problem, atleast now the description is correct lol
